deploy:
  - provider: script
    script: cat composer.json
    on:
      tags: true
  - provider: script
    script: rm -rf composer.json && mv dev.composer.json composer.json
    on:
      all_branches: true

language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer config -g process-timeout 900 && composer update
  - phpenv config-rm xdebug.ini


script:
  - composer test